2025-01-15 15:38:21,895 INFO: Flask app started [in /home/vkataria/nosuHackathon/NOSUHackathon/backend/app/__init__.py:51]
2025-01-15 16:00:17,262 INFO: Flask app started [in /home/vkataria/nosuHackathon/NOSUHackathon/backend/app/__init__.py:51]
2025-01-15 16:00:30,576 ERROR: Exception on /api/test-grader [POST] [in /home/vkataria/nosuHackathon/NOSUHackathon/backend/env/lib/python3.10/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/vkataria/nosuHackathon/NOSUHackathon/backend/env/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vkataria/nosuHackathon/NOSUHackathon/backend/env/lib/python3.10/site-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/vkataria/nosuHackathon/NOSUHackathon/backend/env/lib/python3.10/site-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
  File "/home/vkataria/nosuHackathon/NOSUHackathon/backend/env/lib/python3.10/site-packages/flask/app.py", line 1212, in make_response
    raise TypeError(
TypeError: The view function for 'api.document_pipeline' did not return a valid response. The function either returned None or ended without a return statement.
2025-01-15 16:04:11,545 INFO: Flask app started [in /home/vkataria/nosuHackathon/NOSUHackathon/backend/app/__init__.py:51]
2025-01-15 16:04:26,377 ERROR: Exception on /api/test-grader [POST] [in /home/vkataria/nosuHackathon/NOSUHackathon/backend/env/lib/python3.10/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/vkataria/nosuHackathon/NOSUHackathon/backend/env/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vkataria/nosuHackathon/NOSUHackathon/backend/env/lib/python3.10/site-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/vkataria/nosuHackathon/NOSUHackathon/backend/env/lib/python3.10/site-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
  File "/home/vkataria/nosuHackathon/NOSUHackathon/backend/env/lib/python3.10/site-packages/flask/app.py", line 1212, in make_response
    raise TypeError(
TypeError: The view function for 'api.document_pipeline' did not return a valid response. The function either returned None or ended without a return statement.
2025-01-15 16:10:06,898 ERROR: Exception on /api/test-grader [POST] [in /home/vkataria/nosuHackathon/NOSUHackathon/backend/env/lib/python3.10/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/vkataria/nosuHackathon/NOSUHackathon/backend/env/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vkataria/nosuHackathon/NOSUHackathon/backend/env/lib/python3.10/site-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/vkataria/nosuHackathon/NOSUHackathon/backend/env/lib/python3.10/site-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
  File "/home/vkataria/nosuHackathon/NOSUHackathon/backend/env/lib/python3.10/site-packages/flask/app.py", line 1212, in make_response
    raise TypeError(
TypeError: The view function for 'api.document_pipeline' did not return a valid response. The function either returned None or ended without a return statement.
